// src/App.tsx
import React, { useState, useEffect } from 'react';
import { Navbar } from './components/Navbar';
import { BannerSlider } from './components/BannerSlider';
import { ProductCard } from './components/ProductCard';
import { ProductDetailModal } from './components/ProductDetailModal';
import { CartDrawer } from './components/CartDrawer';
import { CheckoutModal } from './components/CheckoutModal';
import { BankGatewayModal } from './components/BankGatewayModal';
import { OrderTrackerModal } from './components/OrderTrackerModal';
import { AiAssistantModal } from './components/AiAssistantModal';
import { StationeryBackground } from './components/StationeryBackground';
import { Footer } from './components/Footer';
import { Product, CartItem, MenuItem, Order } from './types';
import { MAIN_MENUS, MOCK_PRODUCTS } from './data/mockData';
import { Sparkles, SlidersHorizontal, BookOpen, PenTool, Check, ArrowUp, Layers } from 'lucide-react';

export default function App() {
  const [products, setProducts] = useState<Product[]>(MOCK_PRODUCTS);
  const [menus, setMenus] = useState<MenuItem[]>(MAIN_MENUS);
  const [loading, setLoading] = useState(false);

  // Active Filter State
  const [activeCategoryId, setActiveCategoryId] = useState<string | null>(null);
  const [activeSubcategoryId, setActiveSubcategoryId] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [sortBy, setSortBy] = useState('popular');

  // Shopping Cart State
  const [cartItems, setCartItems] = useState<CartItem[]>([]);
  const [cartOpen, setCartOpen] = useState(false);

  // Modal States
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [checkoutOpen, setCheckoutOpen] = useState(false);
  const [appliedDiscountAmount, setAppliedDiscountAmount] = useState(0);

  // Bank Payment Gateway Modal
  const [bankGatewayOpen, setBankGatewayOpen] = useState(false);
  const [bankOrder, setBankOrder] = useState<Order | null>(null);

  const [trackerOpen, setTrackerOpen] = useState(false);
  const [aiModalOpen, setAiModalOpen] = useState(false);

  // Toast notification
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3000);
  };

  // Fetch Products from Express Backend
  useEffect(() => {
    const fetchProducts = async () => {
      setLoading(true);
      try {
        const params = new URLSearchParams();
        if (activeCategoryId) params.append('category', activeCategoryId);
        if (activeSubcategoryId) params.append('subcategory', activeSubcategoryId);
        if (searchQuery) params.append('search', searchQuery);
        if (sortBy) params.append('sort', sortBy);

        const res = await fetch(`/api/products?${params.toString()}`);
        if (res.ok) {
          const data = await res.json();
          setProducts(data);
        } else {
          setProducts(MOCK_PRODUCTS);
        }
      } catch (err) {
        console.warn('Using local products fallback:', err);
        setProducts(MOCK_PRODUCTS);
      } finally {
        setLoading(false);
      }
    };

    fetchProducts();
  }, [activeCategoryId, activeSubcategoryId, searchQuery, sortBy]);

  // Handle Category & Subcategory Select
  const handleSelectCategory = (catId: string | null, subId: string | null) => {
    setActiveCategoryId(catId);
    setActiveSubcategoryId(subId);
    window.scrollTo({ top: 380, behavior: 'smooth' });
  };

  // Add to Cart
  const handleAddToCart = (product: Product, selectedColor?: string, quantity: number = 1) => {
    setCartItems((prev) => {
      const existing = prev.find((item) => item.product.id === product.id);
      if (existing) {
        return prev.map((item) =>
          item.product.id === product.id
            ? { ...item, quantity: item.quantity + quantity }
            : item
        );
      }
      return [
        ...prev,
        {
          product,
          quantity,
          selectedColor: selectedColor || product.colorOptions?.[0] || 'اصلی',
        },
      ];
    });

    showToast(`🌸 ${product.title} به سبد خرید اضافه شد!`);
  };

  // Update Cart Quantity
  const handleUpdateQuantity = (productId: string, delta: number) => {
    setCartItems((prev) =>
      prev
        .map((item) => {
          if (item.product.id === productId) {
            const newQty = item.quantity + delta;
            return newQty > 0 ? { ...item, quantity: newQty } : null;
          }
          return item;
        })
        .filter(Boolean) as CartItem[]
    );
  };

  // Remove Item from Cart
  const handleRemoveItem = (productId: string) => {
    setCartItems((prev) => prev.filter((item) => item.product.id !== productId));
  };

  const cartCount = cartItems.reduce((acc, item) => acc + item.quantity, 0);

  // Active Menu Label
  const activeMenuObj = menus.find((m) => m.categoryId === activeCategoryId);

  return (
    <div className="min-h-screen relative flex flex-col font-vazir text-slate-800 bg-[#fcf8fc]">
      {/* Stationery Notebook & Pencil Floating Canvas Background */}
      <StationeryBackground />

      {/* Navigation Header with 6 Main Menus + 8 Submenus Integrated */}
      <Navbar
        menus={menus}
        activeCategoryId={activeCategoryId}
        activeSubcategoryId={activeSubcategoryId}
        onSelectCategory={handleSelectCategory}
        cartCount={cartCount}
        onOpenCart={() => setCartOpen(true)}
        onOpenAiModal={() => setAiModalOpen(true)}
        onOpenTrackerModal={() => setTrackerOpen(true)}
        searchQuery={searchQuery}
        setSearchQuery={setSearchQuery}
      />

      {/* Toast Notification */}
      {toastMessage && (
        <div className="fixed bottom-6 left-6 z-50 bg-purple-900 text-white font-bold text-xs px-4 py-3 rounded-2xl shadow-2xl border border-pink-300 flex items-center gap-2 animate-bounce">
          <Check className="w-4 h-4 text-green-400" />
          <span>{toastMessage}</span>
        </div>
      )}

      <main className="flex-1 relative z-10 pb-12">
        {/* Banner Showcase with Left-to-Right Animated Image Slider & Marquee */}
        {!activeCategoryId && !activeSubcategoryId && !searchQuery && (
          <BannerSlider
            onSelectSubcategory={(subId) => handleSelectCategory(null, subId)}
            onOpenAiModal={() => setAiModalOpen(true)}
          />
        )}

        {/* Main Products Section */}
        <div className="max-w-7xl mx-auto px-4 mt-6">
          {/* Section Heading & Sorting Bar */}
          <div className="bg-white/95 backdrop-blur-md rounded-3xl p-5 border-2 border-dashed border-pink-300 shadow-md mb-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2">
                <span className="bg-pink-100 text-pink-700 text-[10px] font-bold px-2.5 py-0.5 rounded-full border border-pink-300">
                  {activeMenuObj ? activeMenuObj.label : 'صفحه اختصاصی محصولات'}
                </span>
                <span className="bg-purple-100 text-purple-800 text-[10px] font-bold px-2.5 py-0.5 rounded-full border border-purple-300 flex items-center gap-1">
                  <Layers className="w-3 h-3 text-purple-600" />
                  <span>۲۵ محصول اختصاصی این منو</span>
                </span>
              </div>
              
              <h2 className="text-xl md:text-2xl font-black font-display text-purple-950 flex items-center gap-2 mt-1">
                <BookOpen className="w-6 h-6 text-pink-500" />
                <span>
                  {activeSubcategoryId
                    ? 'محصولات زیرمنوی انتخابی'
                    : activeCategoryId
                    ? `صفحه اختصاصی: ${activeMenuObj?.label || 'محصولات منو'}`
                    : searchQuery
                    ? `نتایج جستجو برای "${searchQuery}"`
                    : 'صفحه اصلی و کاتالوگ جامع لوازم تحریر'}
                </span>
              </h2>
              <p className="text-xs text-gray-500 mt-1">
                نمایش دقیق {products.length} محصول اختصاصی در این صفحه همراه با دور کادر نقطه‌چین ممتد
              </p>
            </div>

            {/* Sorting Controls */}
            <div className="flex items-center gap-2 self-end sm:self-auto text-xs">
              <SlidersHorizontal className="w-4 h-4 text-pink-500" />
              <span className="font-bold text-slate-700">مرتب‌سازی:</span>
              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value)}
                className="bg-pink-50 border border-pink-200 rounded-xl px-3 py-1.5 font-medium text-xs focus:outline-none focus:ring-2 focus:ring-purple-400"
              >
                <option value="popular">محبوب‌ترین‌ها</option>
                <option value="price-low">ارزان‌ترین</option>
                <option value="price-high">گران‌ترین</option>
                <option value="rating">بالاترین امتیاز</option>
              </select>

              {(activeCategoryId || activeSubcategoryId || searchQuery) && (
                <button
                  onClick={() => {
                    setActiveCategoryId(null);
                    setActiveSubcategoryId(null);
                    setSearchQuery('');
                  }}
                  className="bg-pink-100 text-pink-700 text-xs font-bold px-3 py-1.5 rounded-xl hover:bg-pink-200"
                >
                  بازگشت به همه
                </button>
              )}
            </div>
          </div>

          {/* Product Grid */}
          {loading ? (
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {[...Array(8)].map((_, i) => (
                <div
                  key={i}
                  className="h-80 bg-pink-100/50 rounded-3xl animate-pulse border-2 border-dashed border-pink-300"
                ></div>
              ))}
            </div>
          ) : products.length === 0 ? (
            <div className="text-center py-16 bg-white/80 rounded-3xl border-2 border-dashed border-pink-300 p-8 space-y-3">
              <PenTool className="w-12 h-12 text-pink-400 mx-auto" />
              <h3 className="font-bold text-slate-700 text-base">محصولی در این بخش یافت نشد!</h3>
              <p className="text-xs text-gray-500">
                لطفاً عبارت دیگری را جستجو کنید یا فیلتر دسته‌بندی را تغییر دهید.
              </p>
              <button
                onClick={() => {
                  setActiveCategoryId(null);
                  setActiveSubcategoryId(null);
                  setSearchQuery('');
                }}
                className="bg-purple-600 text-white font-bold text-xs px-5 py-2.5 rounded-full shadow-md hover:bg-purple-700"
              >
                مشاهده همه ۲۵ محصول منو
              </button>
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {products.map((product) => (
                <ProductCard
                  key={product.id}
                  product={product}
                  onSelectProduct={(p) => setSelectedProduct(p)}
                  onAddToCart={handleAddToCart}
                />
              ))}
            </div>
          )}
        </div>
      </main>

      {/* Floating AI Assistant Trigger Button at Bottom-Right */}
      <button
        onClick={() => setAiModalOpen(true)}
        className="fixed bottom-6 right-6 z-40 bg-gradient-to-r from-pink-500 via-purple-600 to-indigo-600 text-white font-bold text-xs p-3.5 rounded-full shadow-2xl hover:scale-110 active:scale-95 transition-all flex items-center gap-2 border-2 border-white"
        title="مشاور هوشمند خرید لوازم تحریر"
      >
        <Sparkles className="w-5 h-5 text-yellow-300 animate-spin-slow" />
        <span className="hidden md:inline font-display text-sm">مشاور هوشمند AI</span>
      </button>

      {/* Footer */}
      <Footer onSelectCategory={handleSelectCategory} />

      {/* Modals */}
      <ProductDetailModal
        product={selectedProduct}
        onClose={() => setSelectedProduct(null)}
        onAddToCart={handleAddToCart}
      />

      <CartDrawer
        isOpen={cartOpen}
        onClose={() => setCartOpen(false)}
        cartItems={cartItems}
        onUpdateQuantity={handleUpdateQuantity}
        onRemoveItem={handleRemoveItem}
        onProceedToCheckout={(discount) => {
          setAppliedDiscountAmount(discount);
          setCheckoutOpen(true);
        }}
      />

      <CheckoutModal
        isOpen={checkoutOpen}
        onClose={() => setCheckoutOpen(false)}
        cartItems={cartItems}
        appliedDiscountAmount={appliedDiscountAmount}
        onOrderSuccess={(order) => {
          setCartItems([]);
          setAppliedDiscountAmount(0);
        }}
        onProceedToBankGateway={(order) => {
          setCheckoutOpen(false);
          setBankOrder(order);
          setBankGatewayOpen(true);
        }}
      />

      {/* Shaparak Bank Gateway Payment Modal */}
      <BankGatewayModal
        isOpen={bankGatewayOpen}
        order={bankOrder}
        onClose={() => setBankGatewayOpen(false)}
        onPaymentSuccess={(orderId, refCode) => {
          showToast(`💳 پرداخت درگاه بانکی با موفقیت ثبت شد! شماره ارجاع: ${refCode}`);
        }}
      />

      <OrderTrackerModal
        isOpen={trackerOpen}
        onClose={() => setTrackerOpen(false)}
      />

      <AiAssistantModal
        isOpen={aiModalOpen}
        onClose={() => setAiModalOpen(false)}
        onAddToCart={(p) => handleAddToCart(p)}
      />
    </div>
  );
}

// src/app/app.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { StationeryService } from './services/stationery.service';
import { MenuItem, Category, Product, CartItem, Order } from '../types';
import { NavbarComponent } from './components/navbar.component';
import { ProductCardComponent } from './components/product-card.component';
import { ProductDetailModalComponent } from './components/product-detail-modal.component';
import { CartDrawerComponent } from './components/cart-drawer.component';
import { CheckoutModalComponent } from './components/checkout-modal.component';
import { BankGatewayModalComponent } from './components/bank-gateway-modal.component';
import { OrderTrackerModalComponent } from './components/order-tracker-modal.component';
import { AiAssistantModalComponent } from './components/ai-assistant-modal.component';
import { StationeryBackgroundComponent } from './components/stationery-background.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    NavbarComponent,
    ProductCardComponent,
    ProductDetailModalComponent,
    CartDrawerComponent,
    CheckoutModalComponent,
    BankGatewayModalComponent,
    OrderTrackerModalComponent,
    AiAssistantModalComponent,
    StationeryBackgroundComponent,
  ],
  template: `
    <div class="min-h-screen relative flex flex-col font-vazir text-slate-800 bg-[#fcf8fc] dir-rtl">
      <!-- Animated Background Canvas -->
      <app-stationery-background />

      <!-- Top Toast Message -->
      @if (toastMessage()) {
        <div class="fixed bottom-5 right-5 z-50 bg-purple-950 text-white text-xs font-bold px-4 py-3 rounded-2xl shadow-2xl border-2 border-pink-400 flex items-center gap-2 animate-bounce">
          <span>🌸</span>
          <span>{{ toastMessage() }}</span>
        </div>
      }

      <!-- Header & Navbar -->
      <app-navbar
        [menus]="menus()"
        [cartCount]="cartCount"
        [activeCategoryId]="activeCategoryId()"
        [activeSubcategoryId]="activeSubcategoryId()"
        [searchQuery]="searchQuery()"
        (selectCategory)="onSelectCategory($event)"
        (searchChange)="onSearchChange($event)"
        (openCart)="cartOpen.set(true)"
        (openTracker)="trackerOpen.set(true)"
        (openAiModal)="aiModalOpen.set(true)"
      />

      <!-- Hero Header Banner -->
      <div class="max-w-7xl mx-auto px-4 pt-6 w-full">
        <div class="relative bg-gradient-to-r from-pink-500 via-purple-600 to-indigo-700 text-white rounded-3xl p-6 sm:p-8 shadow-xl overflow-hidden">
          <div class="relative z-10 max-w-xl space-y-3">
            <span class="inline-block bg-white/20 backdrop-blur-md px-3 py-1 rounded-full text-xs font-black text-yellow-300">
              جدیدترین کلکسیون ۱۴۰۵
            </span>
            <h1 class="text-2xl sm:text-4xl font-black font-display tracking-tight leading-tight">
              دنیای فانتزی لوازم تحریر صورتی و بنفش
            </h1>
            <p class="text-xs sm:text-sm text-pink-100 leading-relaxed font-medium">
              انواع دفترچه‌های ۱۰۰ برگ، کلاسورهای جلد سخت، مداد رنگی‌های حرفه‌ای، هایلایترهای پاستیلی معطر و ست‌های هدیه با تضمین اصالت کالا
            </p>
            <div class="flex flex-wrap gap-2 pt-2">
              <button
                (click)="aiModalOpen.set(true)"
                class="bg-yellow-300 hover:bg-yellow-400 text-purple-950 px-5 py-2.5 rounded-2xl font-black text-xs shadow-md transition-all active:scale-95 flex items-center gap-1.5"
              >
                <span>✨ مشاوره خرید با هوش مصنوعی</span>
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Main Content & Catalog -->
      <main class="max-w-7xl mx-auto px-4 mt-6 flex-1 w-full pb-16">
        <!-- Filter & Heading Bar -->
        <div class="bg-white/95 backdrop-blur-md rounded-3xl p-5 border-2 border-dashed border-pink-300 shadow-md mb-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <div class="flex items-center gap-2">
              <span class="bg-pink-100 text-pink-700 text-[10px] font-bold px-2.5 py-0.5 rounded-full border border-pink-300">
                {{ activeMenuLabel() }}
              </span>
              <span class="bg-purple-100 text-purple-800 text-[10px] font-bold px-2.5 py-0.5 rounded-full border border-purple-300">
                ۲۵ محصول اختصاصی این منو
              </span>
            </div>
            
            <h2 class="text-lg md:text-xl font-black font-display text-purple-950 mt-1">
              {{ headingTitle() }}
            </h2>
            <p class="text-xs text-gray-500 mt-0.5">
              نمایش {{ products().length }} محصول با کیفیت عالی و دور کادر نقطه‌چین ممتد
            </p>
          </div>

          <!-- Sorting Controls -->
          <div class="flex items-center gap-2 w-full sm:w-auto justify-end">
            <span class="text-xs font-bold text-slate-600 whitespace-nowrap">مرتب‌سازی:</span>
            <select
              [ngModel]="sortBy()"
              (ngModelChange)="onSortChange($event)"
              class="bg-pink-50 border border-pink-200 rounded-xl px-3 py-1.5 text-xs font-bold text-slate-700 focus:outline-none focus:border-pink-500"
            >
              <option value="newest">جدیدترین‌ها</option>
              <option value="price-low">ارزان‌ترین</option>
              <option value="price-high">گران‌ترین</option>
              <option value="rating">محبوب‌ترین (امتیاز)</option>
            </select>
          </div>
        </div>

        <!-- Loading Skeleton -->
        @if (loading()) {
          <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
            @for (i of [1,2,3,4,5,6,7,8,9,10]; track i) {
              <div class="h-80 bg-pink-100/50 rounded-3xl animate-pulse border-2 border-dashed border-pink-300"></div>
            }
          </div>
        } @else if (products().length === 0) {
          <div class="text-center py-16 bg-white/80 rounded-3xl border-2 border-dashed border-pink-300 p-8 space-y-3">
            <span class="text-4xl block">✏️</span>
            <h3 class="font-bold text-slate-700 text-base">محصولی در این بخش یافت نشد!</h3>
            <button
              (click)="onSelectCategory({ catId: null, subId: null })"
              class="bg-purple-600 text-white font-bold text-xs px-5 py-2.5 rounded-full shadow-md"
            >
              مشاهده همه ۲۵ محصول منو
            </button>
          </div>
        } @else {
          <!-- Products Grid -->
          <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
            @for (product of products(); track product.id) {
              <app-product-card
                [product]="product"
                (onSelect)="selectedProduct.set($event)"
                (addToCart)="addToCart($event)"
              />
            }
          </div>
        }
      </main>

      <!-- Footer -->
      <footer class="bg-slate-900 text-slate-300 py-10 border-t-4 border-pink-500 mt-auto dir-rtl">
        <div class="max-w-7xl mx-auto px-4 grid grid-cols-1 md:grid-cols-3 gap-8">
          <div>
            <h3 class="font-black text-white text-base font-display mb-2">فروشگاه لوازم تحریر صورتی و بنفش</h3>
            <p class="text-xs text-slate-400 leading-relaxed">
              مرکز تخصصی عرضه انواع نوشت‌افزار فانتزی، دفترچه‌های یادداشت، کلاسورهای جلد سخت و لوازم طراحی پاستیلی با بهترین کیفیت و ارسال به تمام نقاط ایران.
            </p>
          </div>

          <div>
            <h4 class="font-bold text-white text-xs mb-3">دسترسی سریع</h4>
            <ul class="text-xs space-y-2 text-slate-400">
              <li>• دفتر و کاغذ</li>
              <li>• نوشت‌افزار و هایلایتر</li>
              <li>• لوازم طراحی و هنری</li>
              <li>• پکیج‌های کادویی و هدیه</li>
            </ul>
          </div>

          <div>
            <h4 class="font-bold text-white text-xs mb-3">پشتیبانی و تماس</h4>
            <div class="text-xs space-y-2 text-slate-400">
              <p>📍 آدرس: تهران، خیابان انقلاب، مجتمع تحریر، واحد ۳۰۴</p>
              <p>📞 تلفن پشتیبانی: ۰۲۱-۸۸۹۹۰۰۱۱</p>
              <p>⏰ ساعات کاری: شنبه تا پنجشنبه ۹ تا ۲۰</p>
            </div>
          </div>
        </div>
      </footer>

      <!-- Modals & Drawers -->
      <app-product-detail-modal
        [product]="selectedProduct()"
        (onClose)="selectedProduct.set(null)"
        (addToCart)="addToCartWithColor($event)"
      />

      <app-cart-drawer
        [isOpen]="cartOpen()"
        [cartItems]="cartItems()"
        [discountAmount]="discountAmount()"
        (onClose)="cartOpen.set(false)"
        (removeItem)="removeItem($event)"
        (updateQuantity)="updateQuantity($event)"
        (applyCouponCode)="applyCoupon($event)"
        (onCheckout)="openCheckout()"
      />

      <app-checkout-modal
        [isOpen]="checkoutOpen()"
        [cartItems]="cartItems()"
        [discountAmount]="discountAmount()"
        (onClose)="checkoutOpen.set(false)"
        (onSubmitOrder)="handleOrderSubmit($event)"
      />

      <app-bank-gateway-modal
        [isOpen]="bankGatewayOpen()"
        [order]="bankOrder()"
        (onClose)="bankGatewayOpen.set(false)"
      />

      <app-order-tracker-modal
        [isOpen]="trackerOpen()"
        (onClose)="trackerOpen.set(false)"
      />

      <app-ai-assistant-modal
        [isOpen]="aiModalOpen()"
        (onClose)="aiModalOpen.set(false)"
        (selectProduct)="selectedProduct.set($event)"
      />
    </div>
  `
})
export class AppComponent implements OnInit {
  menus = signal<MenuItem[]>([]);
  categories = signal<Category[]>([]);
  products = signal<Product[]>([]);

  activeCategoryId = signal<string | null>(null);
  activeSubcategoryId = signal<string | null>(null);
  searchQuery = signal<string>('');
  sortBy = signal<string>('newest');

  selectedProduct = signal<Product | null>(null);
  cartOpen = signal<boolean>(false);
  checkoutOpen = signal<boolean>(false);
  bankGatewayOpen = signal<boolean>(false);
  bankOrder = signal<Order | null>(null);
  trackerOpen = signal<boolean>(false);
  aiModalOpen = signal<boolean>(false);

  loading = signal<boolean>(false);
  toastMessage = signal<string>('');

  constructor(private stationeryService: StationeryService) {}

  ngOnInit() {
    this.loadMenus();
    this.loadProducts();
  }

  get cartItems() {
    return this.stationeryService.cartItems;
  }

  get discountAmount() {
    return this.stationeryService.appliedDiscountAmount;
  }

  get cartCount(): number {
    return this.cartItems().reduce((acc, item) => acc + item.quantity, 0);
  }

  loadMenus() {
    this.stationeryService.getMenus().subscribe(res => {
      this.menus.set(res.mainMenus);
    });
    this.stationeryService.getCategories().subscribe(cats => {
      this.categories.set(cats);
    });
  }

  loadProducts() {
    this.loading.set(true);
    this.stationeryService.getProducts({
      category: this.activeCategoryId() || undefined,
      subcategory: this.activeSubcategoryId() || undefined,
      search: this.searchQuery() || undefined,
      sort: this.sortBy(),
    }).subscribe(prods => {
      this.loading.set(false);
      this.products.set(prods);
    });
  }

  onSelectCategory(evt: { catId: string | null; subId: string | null }) {
    this.activeCategoryId.set(evt.catId);
    this.activeSubcategoryId.set(evt.subId);
    this.loadProducts();
  }

  onSearchChange(q: string) {
    this.searchQuery.set(q);
    this.loadProducts();
  }

  onSortChange(s: string) {
    this.sortBy.set(s);
    this.loadProducts();
  }

  addToCart(product: Product) {
    this.stationeryService.addToCart(product);
    this.showToast(`«${product.title}» به سبد خرید اضافه شد.`);
  }

  addToCartWithColor(evt: { product: Product; color?: string }) {
    this.stationeryService.addToCart(evt.product, evt.color);
    this.showToast(`«${evt.product.title}» به سبد اضافه شد.`);
  }

  removeItem(idx: number) {
    this.stationeryService.removeFromCart(idx);
  }

  updateQuantity(evt: { index: number; qty: number }) {
    this.stationeryService.updateQuantity(evt.index, evt.qty);
  }

  applyCoupon(code: string) {
    const total = this.stationeryService.getCartTotal();
    this.stationeryService.validateCoupon(code, total).subscribe(res => {
      if (res.valid && res.discountAmount) {
        this.stationeryService.appliedDiscountAmount.set(res.discountAmount);
        this.showToast(res.message);
      } else {
        this.showToast(res.message);
      }
    });
  }

  openCheckout() {
    this.cartOpen.set(false);
    this.checkoutOpen.set(true);
  }

  handleOrderSubmit(orderData: any) {
    this.stationeryService.createOrder(orderData).subscribe(res => {
      if (res.success && res.order) {
        this.checkoutOpen.set(false);
        this.stationeryService.clearCart();
        if (orderData.paymentMethod === 'درگاه آنلاین') {
          this.bankOrder.set(res.order);
          this.bankGatewayOpen.set(true);
        } else {
          this.showToast(`سفارش شما با کد پیگیری ${res.order.trackingCode} ثبت گردید!`);
        }
      }
    });
  }

  showToast(msg: string) {
    this.toastMessage.set(msg);
    setTimeout(() => {
      this.toastMessage.set('');
    }, 3500);
  }

  activeMenuLabel(): string {
    if (!this.activeCategoryId()) return 'صفحه اصلی و کاتالوگ جامع';
    const found = this.menus().find(m => m.categoryId === this.activeCategoryId());
    return found ? found.label : 'محصولات منو';
  }

  headingTitle(): string {
    if (this.searchQuery()) return `نتایج جستجو برای "${this.searchQuery()}"`;
    if (this.activeCategoryId()) {
      const found = this.menus().find(m => m.categoryId === this.activeCategoryId());
      return found ? `صفحه اختصاصی: ${found.label}` : 'محصولات انتخاب شده';
    }
    return 'جدیدترین و محبوب‌ترین لوازم تحریر صورتی و بنفش';
  }
}
