// src/app/components/product-detail-modal.component.ts
import { Component, EventEmitter, Input, Output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Product } from '../../types';

@Component({
  selector: 'app-product-detail-modal',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (product) {
      <div class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-sm overflow-y-auto animate-fadeIn dir-rtl">
        <div class="relative w-full max-w-3xl bg-white/95 rounded-3xl shadow-2xl border-2 border-pink-300 overflow-hidden my-8 max-h-[90vh] flex flex-col md:flex-row">
          
          <!-- Close Button -->
          <button
            (click)="onClose.emit()"
            class="absolute top-4 left-4 z-20 w-8 h-8 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-700 flex items-center justify-center font-bold transition-colors"
          >
            ✕
          </button>

          <!-- Product Image & Gallery -->
          <div class="md:w-1/2 p-6 bg-pink-50/50 flex flex-col items-center justify-center border-b md:border-b-0 md:border-l border-pink-100">
            <div class="relative w-full aspect-square rounded-2xl overflow-hidden shadow-inner bg-white mb-4">
              <img
                [src]="selectedImg()"
                [alt]="product.title"
                class="w-full h-full object-cover"
              />
            </div>

            @if (product.additionalImages && product.additionalImages.length > 0) {
              <div class="flex gap-2">
                @for (img of [product.image, ...product.additionalImages]; track img) {
                  <button
                    (click)="selectedImg.set(img)"
                    [class]="selectedImg() === img ? 'ring-2 ring-pink-500 scale-105' : 'opacity-70'"
                    class="w-12 h-12 rounded-xl overflow-hidden border border-pink-200 transition-all"
                  >
                    <img [src]="img" class="w-full h-full object-cover" />
                  </button>
                }
              </div>
            }
          </div>

          <!-- Product Details -->
          <div class="md:w-1/2 p-6 flex flex-col justify-between space-y-4 overflow-y-auto">
            <div>
              <div class="flex items-center gap-2 mb-2">
                <span class="bg-pink-100 text-pink-700 text-[10px] font-bold px-2.5 py-0.5 rounded-full border border-pink-200">
                  {{ product.category }}
                </span>
                <span class="text-xs text-gray-500">برند: {{ product.brand }}</span>
              </div>

              <h2 class="text-lg font-black text-slate-900 font-display mb-2">
                {{ product.title }}
              </h2>

              <div class="flex items-center gap-2 text-xs mb-3">
                <span class="text-amber-400 font-bold">★ {{ product.rating }}</span>
                <span class="text-gray-400">({{ product.reviewsCount }} دیدگاه خریداران)</span>
              </div>

              <p class="text-xs text-slate-600 leading-relaxed mb-4">
                {{ product.description }}
              </p>

              <!-- Features List -->
              @if (product.features) {
                <div class="bg-pink-50/60 p-3 rounded-2xl border border-pink-100 mb-4">
                  <span class="text-xs font-bold text-purple-900 block mb-2">ویژگی‌های برجسته:</span>
                  <ul class="text-[11px] text-slate-700 space-y-1">
                    @for (feat of product.features; track feat) {
                      <li class="flex items-center gap-1.5">
                        <span class="text-pink-500">✓</span>
                        <span>{{ feat }}</span>
                      </li>
                    }
                  </ul>
                </div>
              }

              <!-- Color Selection -->
              @if (product.colorOptions && product.colorOptions.length > 0) {
                <div class="mb-4">
                  <span class="text-xs font-bold text-slate-700 block mb-2">انتخاب رنگ:</span>
                  <div class="flex gap-2">
                    @for (color of product.colorOptions; track color) {
                      <button
                        (click)="selectedColor.set(color)"
                        [class]="selectedColor() === color ? 'bg-purple-600 text-white font-bold' : 'bg-slate-100 text-slate-700'"
                        class="px-3 py-1.5 text-xs rounded-xl border border-slate-200 transition-colors"
                      >
                        {{ color }}
                      </button>
                    }
                  </div>
                </div>
              }
            </div>

            <!-- Price & Add to Cart CTA -->
            <div class="pt-4 border-t border-pink-100 flex items-center justify-between">
              <div>
                @if (product.discountPrice) {
                  <span class="text-xs text-gray-400 line-through block">
                    {{ product.price.toLocaleString('fa-IR') }}
                  </span>
                  <div class="text-lg font-black text-pink-600 font-display">
                    {{ product.discountPrice.toLocaleString('fa-IR') }}
                    <span class="text-xs font-normal text-slate-600">تومان</span>
                  </div>
                } @else {
                  <div class="text-lg font-black text-purple-950 font-display">
                    {{ product.price.toLocaleString('fa-IR') }}
                    <span class="text-xs font-normal text-slate-600">تومان</span>
                  </div>
                }
              </div>

              <button
                (click)="onAdd()"
                class="bg-gradient-to-r from-pink-500 to-purple-600 hover:brightness-110 text-white font-bold text-xs px-6 py-3 rounded-2xl shadow-lg transition-all active:scale-95 flex items-center gap-2"
              >
                <span>افزودن به سبد خرید</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    }
  `
})
export class ProductDetailModalComponent {
  @Input() product: Product | null = null;
  @Output() onClose = new EventEmitter<void>();
  @Output() addToCart = new EventEmitter<{ product: Product; color?: string }>();

  selectedImg = signal<string>('');
  selectedColor = signal<string>('صورتی پاستیلی');

  ngOnChanges() {
    if (this.product) {
      this.selectedImg.set(this.product.image);
      if (this.product.colorOptions && this.product.colorOptions.length > 0) {
        this.selectedColor.set(this.product.colorOptions[0]);
      }
    }
  }

  onAdd() {
    if (this.product) {
      this.addToCart.emit({ product: this.product, color: this.selectedColor() });
      this.onClose.emit();
    }
  }
}

// src/components/ProductDetailModal.tsx
import React, { useState } from 'react';
import { X, Star, ShoppingBag, Check, ShieldCheck, Truck, RefreshCw, PenTool, Sparkles, BookOpen } from 'lucide-react';
import { Product } from '../types';

interface ProductDetailModalProps {
  product: Product | null;
  onClose: () => void;
  onAddToCart: (product: Product, selectedColor?: string, quantity?: number) => void;
}

export const ProductDetailModal: React.FC<ProductDetailModalProps> = ({
  product,
  onClose,
  onAddToCart,
}) => {
  if (!product) return null;

  const [activeImageIndex, setActiveImageIndex] = useState(0);
  const [selectedColor, setSelectedColor] = useState<string>(
    product.colorOptions?.[0] || 'اصلی'
  );
  const [quantity, setQuantity] = useState(1);
  const [added, setAdded] = useState(false);

  const images = product.additionalImages && product.additionalImages.length > 0
    ? product.additionalImages
    : [product.image];

  const handleAdd = () => {
    onAddToCart(product, selectedColor, quantity);
    setAdded(true);
    setTimeout(() => {
      setAdded(false);
      onClose();
    }, 1200);
  };

  const formattedPrice = product.price.toLocaleString('fa-IR');
  const formattedDiscount = product.discountPrice
    ? product.discountPrice.toLocaleString('fa-IR')
    : null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm overflow-y-auto animate-fadeIn">
      <div className="relative w-full max-w-4xl bg-white rounded-3xl shadow-2xl border-2 border-pink-200 overflow-hidden my-8 max-h-[90vh] flex flex-col">
        {/* Header Ribbon */}
        <div className="bg-pink-purple p-4 text-white flex items-center justify-between">
          <div className="flex items-center gap-2">
            <BookOpen className="w-5 h-5 text-yellow-300" />
            <h2 className="font-bold text-sm md:text-base font-display">
              مشخصات کامل {product.title}
            </h2>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-full bg-white/20 hover:bg-white/30 text-white transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-6 flex-1">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Left Column: Image Gallery with Left-to-Right Carousel */}
            <div className="space-y-4">
              <div className="aspect-square rounded-2xl overflow-hidden bg-pink-50 border-2 border-pink-200 shadow-inner relative">
                <img
                  src={images[activeImageIndex]}
                  alt={product.title}
                  referrerPolicy="no-referrer"
                  className="w-full h-full object-cover transition-all duration-500 transform scale-100 hover:scale-105"
                />
                <span className="absolute bottom-3 right-3 bg-purple-900/80 backdrop-blur-md text-white text-[10px] px-3 py-1 rounded-full">
                  تصویر {activeImageIndex + 1} از {images.length}
                </span>
              </div>

              {/* Left to Right Animated Thumbnail Carousel */}
              <div className="flex items-center gap-2 overflow-x-auto pb-2">
                {images.map((img, idx) => (
                  <button
                    key={idx}
                    onClick={() => setActiveImageIndex(idx)}
                    className={`w-16 h-16 rounded-xl overflow-hidden border-2 transition-all flex-shrink-0 ${
                      activeImageIndex === idx
                        ? 'border-purple-600 scale-105 shadow-md'
                        : 'border-pink-200 opacity-60 hover:opacity-100'
                    }`}
                  >
                    <img
                      src={img}
                      alt="تصویر گالری"
                      referrerPolicy="no-referrer"
                      className="w-full h-full object-cover"
                    />
                  </button>
                ))}
              </div>

              {/* Trust Badges */}
              <div className="grid grid-cols-3 gap-2 text-center pt-2 border-t border-pink-100 text-xs text-slate-600">
                <div className="flex flex-col items-center gap-1 p-2 rounded-xl bg-pink-50">
                  <Truck className="w-5 h-5 text-pink-600" />
                  <span className="font-medium text-[11px]">ارسال سریع پیشتاز</span>
                </div>
                <div className="flex flex-col items-center gap-1 p-2 rounded-xl bg-purple-50">
                  <ShieldCheck className="w-5 h-5 text-purple-600" />
                  <span className="font-medium text-[11px]">اصالت ۱۰۰٪ کالا</span>
                </div>
                <div className="flex flex-col items-center gap-1 p-2 rounded-xl bg-pink-50">
                  <RefreshCw className="w-5 h-5 text-pink-600" />
                  <span className="font-medium text-[11px]">۷ روز ضمانت بازگشت</span>
                </div>
              </div>
            </div>

            {/* Right Column: Product Info & Actions */}
            <div className="space-y-5">
              <div>
                <div className="flex items-center gap-2 text-xs text-purple-600 font-bold mb-1">
                  <span>برند: {product.brand}</span>
                  <span>•</span>
                  <span>دسته: {product.category}</span>
                </div>
                <h1 className="text-xl md:text-2xl font-black text-slate-900 leading-snug">
                  {product.title}
                </h1>
              </div>

              {/* Price & Rating */}
              <div className="bg-gradient-to-r from-pink-50 to-purple-50 p-4 rounded-2xl border border-pink-200 flex items-center justify-between">
                <div>
                  <span className="text-xs text-gray-500 block mb-0.5">قیمت مصرف‌کننده:</span>
                  {formattedDiscount ? (
                    <div className="flex items-baseline gap-2">
                      <span className="text-2xl font-black text-pink-600 font-display">
                        {formattedDiscount}
                      </span>
                      <span className="text-sm text-gray-400 line-through">
                        {formattedPrice}
                      </span>
                      <span className="text-xs font-bold text-slate-700">تومان</span>
                    </div>
                  ) : (
                    <div className="flex items-baseline gap-1">
                      <span className="text-2xl font-black text-purple-900 font-display">
                        {formattedPrice}
                      </span>
                      <span className="text-xs font-bold text-slate-700">تومان</span>
                    </div>
                  )}
                </div>

                <div className="flex items-center gap-1.5 bg-white px-3 py-1.5 rounded-xl border border-amber-200 shadow-sm text-sm font-bold text-amber-700">
                  <Star className="w-4 h-4 fill-amber-400 text-amber-400" />
                  <span>{product.rating}</span>
                  <span className="text-xs text-gray-400 font-normal">({product.reviewsCount} نظر)</span>
                </div>
              </div>

              {/* Color Selector */}
              {product.colorOptions && product.colorOptions.length > 0 && (
                <div className="space-y-2">
                  <label className="text-xs font-bold text-slate-700 block">
                    انتخاب تنوع رنگ:
                  </label>
                  <div className="flex flex-wrap gap-2">
                    {product.colorOptions.map((color, idx) => (
                      <button
                        key={idx}
                        onClick={() => setSelectedColor(color)}
                        className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all ${
                          selectedColor === color
                            ? 'bg-purple-600 text-white shadow-md'
                            : 'bg-pink-50 text-slate-700 hover:bg-pink-100 border border-pink-200'
                        }`}
                      >
                        {color}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {/* Quantity Counter */}
              <div className="flex items-center justify-between bg-pink-50/60 p-3 rounded-2xl border border-pink-200">
                <span className="text-xs font-bold text-slate-700">تعداد سفارش:</span>
                <div className="flex items-center gap-3 bg-white px-3 py-1.5 rounded-xl border border-pink-300">
                  <button
                    onClick={() => setQuantity(Math.max(1, quantity - 1))}
                    className="w-7 h-7 rounded-lg bg-pink-100 text-pink-700 font-bold flex items-center justify-center hover:bg-pink-200"
                  >
                    -
                  </button>
                  <span className="font-extrabold text-sm w-6 text-center">{quantity}</span>
                  <button
                    onClick={() => setQuantity(quantity + 1)}
                    className="w-7 h-7 rounded-lg bg-purple-100 text-purple-700 font-bold flex items-center justify-center hover:bg-purple-200"
                  >
                    +
                  </button>
                </div>
              </div>

              {/* Add to Cart CTA */}
              <button
                onClick={handleAdd}
                className={`w-full py-3.5 rounded-2xl font-bold text-sm shadow-xl flex items-center justify-center gap-2 transition-all ${
                  added
                    ? 'bg-green-600 text-white'
                    : 'bg-gradient-to-r from-pink-500 to-purple-600 text-white hover:brightness-110 active:scale-98'
                }`}
              >
                {added ? (
                  <>
                    <Check className="w-5 h-5" />
                    <span>با موفقیت افزوده شد</span>
                  </>
                ) : (
                  <>
                    <ShoppingBag className="w-5 h-5" />
                    <span>افزودن به سبد خرید ({ ( (product.discountPrice || product.price) * quantity ).toLocaleString('fa-IR') } تومان)</span>
                  </>
                )}
              </button>

              {/* Features List */}
              <div className="space-y-2 pt-2 border-t border-pink-100">
                <h3 className="text-xs font-bold text-purple-900 flex items-center gap-1.5">
                  <Sparkles className="w-4 h-4 text-pink-500" />
                  <span>ویژگی‌های کلیدی کالا:</span>
                </h3>
                <ul className="space-y-1.5 text-xs text-slate-600">
                  {product.features.map((feat, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <span className="w-1.5 h-1.5 rounded-full bg-pink-500 mt-1.5 flex-shrink-0"></span>
                      <span>{feat}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Description */}
              <div className="bg-pink-50/40 p-3.5 rounded-2xl text-xs text-slate-700 leading-relaxed border border-pink-100">
                <p>{product.description}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
